services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./service:/service

    environment:
      - DB_HOST=db
      - DB_NAME=dbdjango
      - DB_USER=duser
      - DB_PASSWORD=pass123

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - db

  db:
    ports:
      - "5433:5432"
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbdjango
      - POSTGRES_USER=duser
      - POSTGRES_PASSWORD=pass123