# Generated by Django 3.2.16 on 2024-06-12 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('key_works', models.TextField()),
                ('content', models.TextField()),
                ('active', models.BooleanField()),
                ('lang_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fdc_corp.languages')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='public')),
                ('active', models.BooleanField()),
                ('lang_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fdc_corp.languages')),
            ],
        ),
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=256)),
                ('active', models.BooleanField()),
                ('lang_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fdc_corp.languages')),
            ],
        ),
        migrations.CreateModel(
            name='FooterMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=256)),
                ('active', models.BooleanField()),
                ('lang_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fdc_corp.languages')),
            ],
        ),
    ]
