# Generated by Django 3.2.16 on 2024-06-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdc_corp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footermenu',
            options={'verbose_name': 'Footer Menu', 'verbose_name_plural': 'Footer Menu'},
        ),
        migrations.AlterModelOptions(
            name='languages',
            options={'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterModelOptions(
            name='mainmenu',
            options={'verbose_name': 'Main Menu', 'verbose_name_plural': 'Main Menu'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='pages',
            options={'verbose_name': 'Page', 'verbose_name_plural': 'Pages'},
        ),
        migrations.AddField(
            model_name='footermenu',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pages',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pages',
            name='key_works',
            field=models.TextField(null=True),
        ),
    ]
