# Generated by Django 3.2.16 on 2024-07-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdc_corp', '0003_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='public'),
        ),
    ]
